// Bundles src/lib/ into a single self-contained ES module suitable for
// pasting into Claude.ai Cowork artifacts. No imports — everything lives
// in one file. Output: cowork/roi-lib.mjs
//
// Run with `npm run build:cowork` after any change to the math lib.

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

// Files concatenated in dependency order. format/erlang/curves first
// (leaves), staffing depends on erlang, scenarios depends on staffing,
// presets is standalone.
const FILES = [
  "src/lib/format.js",
  "src/lib/erlang.js",
  "src/lib/arrivalCurves.js",
  "src/lib/staffing.js",
  "src/lib/scenarios.js",
  "src/lib/presets.js",
];

const HEADER = `// ShyftOff ROI math lib — Cowork bundle.
// Generated by scripts/build-cowork.mjs from src/lib/ — do not edit by hand.
// Source of truth: https://github.com/<your-repo>/blob/main/shyftoff-roi/src/lib/
// All functions are pure. See ROI_MODEL_BRIEF.md for usage.

`;

async function bundle() {
  const parts = [HEADER];
  for (const rel of FILES) {
    const src = await readFile(resolve(ROOT, rel), "utf8");
    // Strip relative imports (intra-lib refs). Other import shapes are
    // not used by this lib, so this regex is sufficient.
    const stripped = src.replace(/^import\s+.*?from\s+["']\.\/[^"']+["'];?\s*\n/gm, "");
    parts.push(`// ─── ${rel} ${"─".repeat(72 - rel.length)}\n`);
    parts.push(stripped.trim());
    parts.push("\n\n");
  }
  const out = parts.join("");
  const outPath = resolve(ROOT, "cowork/roi-lib.mjs");
  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, out, "utf8");
  console.log(`Wrote ${outPath} (${out.length.toLocaleString()} bytes)`);
}

bundle().catch((e) => {
  console.error(e);
  process.exit(1);
});
