// ShyftOff ROI math lib — Cowork bundle.
// Generated by scripts/build-cowork.mjs from src/lib/ — do not edit by hand.
// Source of truth: https://github.com/<your-repo>/blob/main/shyftoff-roi/src/lib/
// All functions are pure. See ROI_MODEL_BRIEF.md for usage.

// ─── src/lib/format.js ───────────────────────────────────────────────────────
export const fmt = (n) =>
  new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 }).format(n);

export const fmtD = (n, d = 1) =>
  new Intl.NumberFormat("en-US", {
    minimumFractionDigits: d,
    maximumFractionDigits: d,
  }).format(n);

export const fmtCur = (n) =>
  new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(n);

export const fmtCurD = (n, d = 2) =>
  new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: d,
    maximumFractionDigits: d,
  }).format(n);

// ─── src/lib/erlang.js ───────────────────────────────────────────────────────
// Erlang C math (log-space for numerical stability).

export function logFactorial(n) {
  if (n <= 1) return 0;
  let r = 0;
  for (let i = 2; i <= n; i++) r += Math.log(i);
  return r;
}

export function erlangC(agents, trafficErlangs) {
  const N = agents;
  const A = trafficErlangs;
  if (N <= A) return 1;
  if (A <= 0) return 0;
  const rho = A / N;
  if (rho >= 1) return 1;

  const logAN = N * Math.log(A) - logFactorial(N);

  let logTerm = 0;
  const logTerms = [0];
  for (let k = 1; k < N; k++) {
    logTerm += Math.log(A) - Math.log(k);
    logTerms.push(logTerm);
  }
  const maxLog = Math.max(...logTerms, logAN);
  const sumPart = logTerms.reduce((s, lt) => s + Math.exp(lt - maxLog), 0);

  const scaledAN = Math.exp(logAN - maxLog);
  const numerator = scaledAN * (1 / (1 - rho));
  return numerator / (sumPart + numerator);
}

export function serviceLevel(agents, trafficErlangs, ahtSeconds, targetSeconds) {
  if (agents <= trafficErlangs) return 0;
  if (trafficErlangs <= 0) return 1;
  const pw = erlangC(agents, trafficErlangs);
  const sl =
    1 - pw * Math.exp(-(agents - trafficErlangs) * (targetSeconds / ahtSeconds));
  return Math.max(0, Math.min(1, sl));
}

// Default search: starts at max(1, ceil(traffic)), filters occupancy first.
// Matches AICalculator semantics and is used by the shared staffing/scenarios layer.
export function findRequiredAgents(
  trafficErlangs,
  ahtSeconds,
  targetSL,
  targetSeconds,
  maxOccupancy,
) {
  const minAgents = Math.max(1, Math.ceil(trafficErlangs));
  for (let n = minAgents; n < minAgents + 300; n++) {
    if (trafficErlangs / n > maxOccupancy) continue;
    if (serviceLevel(n, trafficErlangs, ahtSeconds, targetSeconds) >= targetSL)
      return n;
  }
  return minAgents + 300;
}

// Occ-driven staffing: ignores the SL check entirely and returns the minimum
// agent count needed to keep occupancy at or below maxOccupancy. Used when the
// planner has explicitly chosen occupancy as the binding constraint and is
// willing to accept whatever SL falls out. The caller is responsible for
// computing achievedSL = serviceLevel(N, erlangs, ...) and warning the user
// when it drifts below their target.
export function findRequiredAgentsByOcc(trafficErlangs, maxOccupancy) {
  if (trafficErlangs <= 0) return 1;
  if (maxOccupancy <= 0 || maxOccupancy >= 1) {
    // Degenerate inputs: fall back to "just enough for steady-state."
    return Math.max(1, Math.ceil(trafficErlangs));
  }
  return Math.max(1, Math.ceil(trafficErlangs / maxOccupancy));
}

// The "natural" maxOcc for a given traffic profile: the highest occupancy at
// which SL is still met. This is what the maxOcc slider should default to —
// the sweet spot where both constraints are exactly balanced. Below this, the
// user is over-staffing (SL exceeded). Above this, SL drops below target and
// a warning fires. Capped at 0.95 to avoid pathological edge cases.
//
// Math: if N is the smallest agent count satisfying SL, then for ceil(erlangs/
// maxOcc) to still equal N we need maxOcc < erlangs / (N-1). Returning just
// below that bound puts the slider at the highest occ where staffing still
// equals N and SL still meets target. Returning erlangs/N (the lower bound of
// the same plateau) would also preserve N agents but at unnecessarily
// conservative occupancy — same staffing, but the slider would look like it
// "doesn't reach" the actual sweet spot.
export function findNaturalMaxOcc(
  trafficErlangs,
  ahtSeconds,
  targetSL,
  targetSeconds,
) {
  if (trafficErlangs <= 0) return 0.85;
  const minAgents = Math.max(1, Math.ceil(trafficErlangs));
  for (let n = minAgents; n < minAgents + 300; n++) {
    if (serviceLevel(n, trafficErlangs, ahtSeconds, targetSeconds) >= targetSL) {
      if (n <= 1) return 0.95; // trivial-staffing edge case
      return Math.min(0.95, trafficErlangs / (n - 1) - 1e-9);
    }
  }
  return 0.85;
}

// ─── src/lib/arrivalCurves.js ────────────────────────────────────────────────
// 30-min intraday arrival curves. Each entry's pct is unnormalized; consumers
// normalize against the active slice (start/end hour window).

// Single-peak realistic pattern used by the v15 classic calculator:
// overnight low → morning ramp → late-morning peak → lunch dip →
// afternoon secondary → evening taper.
export const SINGLE_PEAK = [
  { label: "00:00", pct: 0.4 }, { label: "00:30", pct: 0.3 },
  { label: "01:00", pct: 0.3 }, { label: "01:30", pct: 0.2 },
  { label: "02:00", pct: 0.2 }, { label: "02:30", pct: 0.2 },
  { label: "03:00", pct: 0.2 }, { label: "03:30", pct: 0.2 },
  { label: "04:00", pct: 0.3 }, { label: "04:30", pct: 0.3 },
  { label: "05:00", pct: 0.5 }, { label: "05:30", pct: 0.7 },
  { label: "06:00", pct: 1.2 }, { label: "06:30", pct: 1.5 },
  { label: "07:00", pct: 2.3 }, { label: "07:30", pct: 3.1 },
  { label: "08:00", pct: 4.5 }, { label: "08:30", pct: 5.8 },
  { label: "09:00", pct: 6.8 }, { label: "09:30", pct: 7.2 },
  { label: "10:00", pct: 7.5 }, { label: "10:30", pct: 7.3 },
  { label: "11:00", pct: 6.9 }, { label: "11:30", pct: 6.2 },
  { label: "12:00", pct: 5.0 }, { label: "12:30", pct: 4.6 },
  { label: "13:00", pct: 5.1 }, { label: "13:30", pct: 5.5 },
  { label: "14:00", pct: 5.8 }, { label: "14:30", pct: 5.4 },
  { label: "15:00", pct: 4.8 }, { label: "15:30", pct: 4.2 },
  { label: "16:00", pct: 3.5 }, { label: "16:30", pct: 2.8 },
  { label: "17:00", pct: 2.1 }, { label: "17:30", pct: 1.8 },
  { label: "18:00", pct: 1.5 }, { label: "18:30", pct: 1.3 },
  { label: "19:00", pct: 1.1 }, { label: "19:30", pct: 0.9 },
  { label: "20:00", pct: 0.8 }, { label: "20:30", pct: 0.7 },
  { label: "21:00", pct: 0.6 }, { label: "21:30", pct: 0.5 },
  { label: "22:00", pct: 0.5 }, { label: "22:30", pct: 0.4 },
  { label: "23:00", pct: 0.4 }, { label: "23:30", pct: 0.4 },
];

// Dual-peak "camel hump" pattern used by the AI calculator. Morning peak
// ~9:30 AM, deep lunch valley ~12:30, secondary afternoon peak ~15:00. The
// two-peak shape maximises shift-block waste — no single 8-hr shift covers
// both humps without running overstaffed through the valley.
export const CAMEL = [
  { label: "00:00", pct: 0.3 }, { label: "00:30", pct: 0.2 },
  { label: "01:00", pct: 0.2 }, { label: "01:30", pct: 0.1 },
  { label: "02:00", pct: 0.1 }, { label: "02:30", pct: 0.1 },
  { label: "03:00", pct: 0.1 }, { label: "03:30", pct: 0.2 },
  { label: "04:00", pct: 0.3 }, { label: "04:30", pct: 0.4 },
  { label: "05:00", pct: 0.7 }, { label: "05:30", pct: 1.0 },
  { label: "06:00", pct: 1.6 }, { label: "06:30", pct: 2.3 },
  { label: "07:00", pct: 3.5 }, { label: "07:30", pct: 5.0 },
  { label: "08:00", pct: 6.5 }, { label: "08:30", pct: 7.8 },
  { label: "09:00", pct: 8.6 }, { label: "09:30", pct: 9.0 },
  { label: "10:00", pct: 8.7 }, { label: "10:30", pct: 7.9 },
  { label: "11:00", pct: 6.5 }, { label: "11:30", pct: 5.0 },
  { label: "12:00", pct: 3.6 }, { label: "12:30", pct: 3.1 },
  { label: "13:00", pct: 3.2 }, { label: "13:30", pct: 4.2 },
  { label: "14:00", pct: 6.0 }, { label: "14:30", pct: 7.5 },
  { label: "15:00", pct: 7.8 }, { label: "15:30", pct: 7.2 },
  { label: "16:00", pct: 6.2 }, { label: "16:30", pct: 4.9 },
  { label: "17:00", pct: 3.5 }, { label: "17:30", pct: 2.6 },
  { label: "18:00", pct: 1.9 }, { label: "18:30", pct: 1.4 },
  { label: "19:00", pct: 1.1 }, { label: "19:30", pct: 0.9 },
  { label: "20:00", pct: 0.7 }, { label: "20:30", pct: 0.5 },
  { label: "21:00", pct: 0.4 }, { label: "21:30", pct: 0.3 },
  { label: "22:00", pct: 0.3 }, { label: "22:30", pct: 0.3 },
  { label: "23:00", pct: 0.3 }, { label: "23:30", pct: 0.3 },
];

// Pure Gaussian centered at midday — the textbook "bell" arrival pattern.
// Symmetric, no lunch dip, no early-morning ramp asymmetry. Useful as a
// reference baseline against the more realistic SINGLE_PEAK and CAMEL.
// mean = interval 24 (12:00), stdDev = 6 intervals (3 hrs), peak ~9%.
function gaussianCurve({ mean, stdDev, peak }) {
  return Array.from({ length: 48 }, (_, i) => {
    const hh = String(Math.floor(i / 2)).padStart(2, "0");
    const mm = i % 2 === 0 ? "00" : "30";
    const pct =
      peak * Math.exp(-((i - mean) ** 2) / (2 * stdDev ** 2));
    return { label: `${hh}:${mm}`, pct: Math.round(pct * 10) / 10 };
  });
}

export const BELL = gaussianCurve({ mean: 24, stdDev: 6, peak: 9 });

// Industry-realistic contact-center day-of-week distribution.
//   • Monday spikes ~40% above Friday (FlyFone published data)
//   • Tuesday-Thursday cluster at steady mid-range
//   • Friday tapers
//   • Weekends drop sharply (most centers operate reduced weekend coverage)
// Sources: flyfone.com/call-center-forecasting,
// brightpattern.com (Mon = busiest day, 9-10 AM spike),
// blog.peopleware.com/forecasting/call-center-forecasting-methods-part-1.
export const DEFAULT_DOW = {
  Mon: 20, Tue: 17, Wed: 16, Thu: 16, Fri: 14, Sat: 9, Sun: 8,
};

// ─── src/lib/staffing.js ─────────────────────────────────────────────────────
import {
  findRequiredAgents,
  findRequiredAgentsByOcc,
  findNaturalMaxOcc,
  serviceLevel,
} from "./erlang.js";

// Greedy shift-block solver: replicates the v15 WFM model. Traditional centers
// schedule fixed shifts with staggered starts; agents work the whole shift, so
// schedules over-cover the demand bathtub. Returns per-shift headcount and the
// scheduled coverage staircase that drives the "overstaffed mid-day,
// understaffed at edges" pattern.
export function solveShiftBlocks(
  intervals,
  shiftLengthHrs,
  shrinkage,
  influxTarget = 1.2,
) {
  const n = intervals.length;
  if (n === 0) return { dailyShiftHours: 0, avgFTE: 0 };

  const intervalsPerShift = shiftLengthHrs * 2;
  // 30-min stagger between shift starts. Real WFM platforms (NICE IEX,
  // Verint, Genesys) use 15-30 min granularity — 1-hour stagger creates only
  // 3 shift slots on a 10-hr window, which forces the solver to flat-cover
  // the mid-day overlap and starve the edges. With 30-min stagger we get 5
  // slots (8:00, 8:30, 9:00, 9:30, 10:00 for an 8-12 hr window), giving the
  // squared-deviation solver a tapered coverage gradient to approximate the
  // U-shaped demand curve more honestly.
  const stagger = 1; // 30-min stagger
  const startWindow = Math.max(0, n - intervalsPerShift);
  const numShifts =
    startWindow > 0 ? Math.max(1, Math.floor(startWindow / stagger) + 1) : 1;

  const shiftDefs = [];
  for (let s = 0; s < numShifts; s++) {
    const si = Math.min(s * stagger, Math.max(0, n - intervalsPerShift));
    const ei = Math.min(si + intervalsPerShift, n);
    shiftDefs.push({ startIdx: si, endIdx: ei, hours: (ei - si) * 0.5 });
  }

  // `target` = heads-in-seats target per interval. We schedule BODIES, not
  // on-phones; bodies × (1 - shrinkage) ≈ on-phones, so to deliver `required`
  // on-phones we need to schedule `required / (1 - shrinkage)` heads-in-seats.
  // (The chart's "Required (Erlang C)" line shows raw `iv.required` separately
  // — that's what a real WFM analyst calls the on-phones requirement.)
  const target = intervals.map((iv) =>
    Math.ceil(iv.required / (1 - shrinkage)),
  );
  const totalRequired = target.reduce((s, v) => s + v, 0);
  // adjustedTarget scales the per-interval goal by the user's coverage choice.
  // At influxTarget = 0.90, every interval aims for 90% of its target — the
  // squared-deviation solver then distributes the under-coverage roughly
  // evenly across intervals instead of bunching it at the edges.
  const adjustedTarget = target.map((t) => t * influxTarget);

  const getSched = (agents) => {
    const sched = new Array(n).fill(0);
    shiftDefs.forEach((sh, i) => {
      for (let j = sh.startIdx; j < sh.endIdx; j++) sched[j] += agents[i];
    });
    return sched;
  };

  // Squared-deviation objective: penalize BOTH over- and under-coverage,
  // with bigger gaps hurting quadratically more. The old one-sided gap (which
  // only counted under-coverage) is the textbook EWFM mistake — it makes
  // over-stuffing "free" so the solver loads up the mid-day shift overlap
  // where one agent helps the most intervals, and starves the edges (e.g.
  // 16:00-18:00 covered by only one shift). Squared deviation makes the
  // solver distribute agents so the worst per-interval gap is minimized,
  // matching how a real WFM analyst builds a schedule.
  const getSquaredGap = (sched) => {
    let gap = 0;
    for (let i = 0; i < n; i++) {
      const d = adjustedTarget[i] - sched[i];
      gap += d * d;
    }
    return gap;
  };

  const shiftAgents = new Array(numShifts).fill(0);
  // Safety cap so a pathological input can't loop forever. Set generously to
  // 2× total adjusted target divided by shifts (each agent contributes to
  // multiple intervals, so this is way more than we'd ever actually need).
  const totalAdjusted = adjustedTarget.reduce((s, v) => s + v, 0);
  const safetyCap = Math.ceil(2 * totalAdjusted / Math.max(1, numShifts)) + 50;

  for (let iter = 0; iter < safetyCap; iter++) {
    const cs = getSched(shiftAgents);
    const currentGap = getSquaredGap(cs);
    let bestShift = -1;
    let bestImprovement = 0;
    for (let s = 0; s < numShifts; s++) {
      const trial = [...shiftAgents];
      trial[s]++;
      const newGap = getSquaredGap(getSched(trial));
      const improvement = currentGap - newGap;
      if (improvement > bestImprovement) {
        bestImprovement = improvement;
        bestShift = s;
      }
    }
    // No shift improves squared deviation — we're at a local optimum: every
    // interval either at or past its adjustedTarget, and adding more agents
    // anywhere would strictly increase the over-coverage penalty.
    if (bestShift === -1) break;
    shiftAgents[bestShift]++;
  }

  const scheduledPerInterval = getSched(shiftAgents);

  // Per-shift utilization: on-phones time / paid time. This is the "what
  // you're paying for vs what you're getting" metric — the sales story most
  // BPO buyers respond to. (We considered industry "occupancy" = on_phones /
  // available_for_calls, but reverted because utilization tells the cost
  // story more directly: every percentage point below 100 is paid-but-not-
  // producing time.)
  //
  // Demand share uses AGENT-WEIGHTED routing (each agent has equal call
  // probability), not the old equal-split. Big shifts now get demand
  // proportional to their headcount — matches how real ACDs route calls.
  //
  // Inefficiency hours = paid_time − on_phones_time. Captures shrinkage AND
  // over-coverage. Every active shift always shows > 0 because shrinkage
  // alone is unavoidable.
  const productionFactor = 1 - shrinkage;
  const shiftMetrics = shiftDefs.map((sh, idx) => {
    const agents = shiftAgents[idx];
    if (!agents) return { avgTarget: 0, inefficiencyHrsDay: 0, utilizationPct: 0 };
    let totalActualOnPhones = 0;
    let totalNeededOnPhones = 0;
    let cnt = 0;
    for (let i = sh.startIdx; i < sh.endIdx; i++) {
      const onPhonesDemand = intervals[i].required;
      let totalActiveAgents = 0;
      for (let j = 0; j < shiftDefs.length; j++) {
        const s2 = shiftDefs[j];
        if (i >= s2.startIdx && i < s2.endIdx && shiftAgents[j] > 0) {
          totalActiveAgents += shiftAgents[j];
        }
      }
      const share = totalActiveAgents > 0 ? agents / totalActiveAgents : 0;
      const propOnPhonesDemand = onPhonesDemand * share;
      const onPhonesCapacity = agents * productionFactor;
      const actualOnPhones = Math.min(onPhonesCapacity, propOnPhonesDemand);
      totalActualOnPhones += actualOnPhones;
      totalNeededOnPhones += propOnPhonesDemand;
      cnt++;
    }
    const avgTarget = cnt > 0 ? totalNeededOnPhones / cnt : 0;
    const totalPaidAgentIntervals = agents * (sh.endIdx - sh.startIdx);
    const inefficiencyHrsDay = (totalPaidAgentIntervals - totalActualOnPhones) * 0.5;
    // Utilization (back to v15 semantic): on_phones / paid_time.
    const utilizationPct =
      totalPaidAgentIntervals > 0
        ? Math.min(100, (totalActualOnPhones / totalPaidAgentIntervals) * 100)
        : 0;
    return { avgTarget, inefficiencyHrsDay, utilizationPct };
  });

  const dailyShiftHours = shiftDefs.reduce(
    (s, sh, i) => s + shiftAgents[i] * sh.hours,
    0,
  );
  const avgFTE = dailyShiftHours / shiftLengthHrs;
  return {
    dailyShiftHours,
    avgFTE,
    shiftAgents,
    shiftDefs,
    scheduledPerInterval,
    shiftMetrics,
  };
}

// Smart break-placement model (replaces the v15 static bathtub).
//
// The old model applied a hardcoded shape per shift (lunch dip at the same
// in-shift position for every shift) which made every shift's lunch stack at
// the same wall-clock time. That's not how a real WFM platform works — NICE
// IEX, Verint, and Genesys all run an intraday-break-optimization pass that
// STAGGERS lunches across overlapping shifts so on-phones tracks demand.
//
// Algorithm (per shift, post body-placement):
//   1. budget_S = shiftAgents_S × shiftLen × inCenterShrink
//      (total agent-intervals of break time this shift owes its agents)
//   2. Greedy: place 1 break-agent-interval at a time. Pick the interval
//      (within shift's active window) where current on-phones MOST EXCEEDS
//      required. This naturally puts breaks during overlap valleys / lunch
//      where adjacent shifts can absorb the coverage hit.
//   3. Subject to a 50% cap per interval (no more than half a shift on break
//      at once — keeps the schedule physically realistic).
//   4. If `rawRequired` isn't provided, fall back to a flat target (placing
//      breaks evenly), which is the backward-compat path.
//
// Finally, out-of-center shrinkage (training, PTO, sick) is applied as a
// flat multiplier because those agents aren't on the floor at all.
//
// Backward compatible: with no shrinkage args, returns scheduled as-is.
export function computeOnPhones(
  shiftDefs,
  shiftAgents,
  n,
  inCenterShrink = 0,
  outOfCenterShrink = 0,
  rawRequired = null,
) {
  // Pass 1: scheduled bodies per interval (what the solver placed).
  const scheduled = new Array(n).fill(0);
  shiftDefs.forEach((sh, idx) => {
    const agents = shiftAgents[idx];
    if (!agents) return;
    for (let i = sh.startIdx; i < sh.endIdx; i++) scheduled[i] += agents;
  });

  // If no in-center shrinkage requested, skip the break solver entirely
  // (backward-compat with v15 callers that pre-date the shrinkage params).
  if (inCenterShrink <= 0) {
    return scheduled.map((s) => Math.round(s * (1 - outOfCenterShrink)));
  }

  // Pass 2: smart break placement, one shift at a time.
  const breaks = new Array(n).fill(0);
  // Track per-shift, per-interval break count so we can enforce the cap
  // without double-counting across shifts.
  const breaksPerShift = shiftDefs.map(() => new Array(n).fill(0));

  shiftDefs.forEach((sh, idx) => {
    const agents = shiftAgents[idx];
    if (!agents) return;
    const shiftLen = sh.endIdx - sh.startIdx;
    let budget = Math.round(agents * shiftLen * inCenterShrink);
    // 50% cap: never more than half a shift on break simultaneously. Real
    // WFM ranges from 25% (strict) to 50% (busy lunch rotation).
    let cap = Math.max(1, Math.ceil(agents * 0.50));

    let safety = 0;
    while (budget > 0 && safety < 100000) {
      safety++;
      let bestI = -1;
      let bestImprovement = -Infinity;
      for (let i = sh.startIdx; i < sh.endIdx; i++) {
        if (breaksPerShift[idx][i] >= cap) continue;
        const currentOnPhones = scheduled[i] - breaks[i];
        if (currentOnPhones <= 0) continue;
        // Where would placing 1 more break most help? If on-phones[i] > target[i]
        // (over-staffed), placing a break here HELPS by reducing the squared
        // deviation. If under-staffed, it hurts. Greedy picks the most-helping
        // (or least-hurting) interval. Improvement = 2(op − target) − 1.
        const target = rawRequired && rawRequired[i] != null
          ? rawRequired[i]
          : 0; // no target info → just trim from highest on-phones (flat-down)
        const improvement = 2 * (currentOnPhones - target) - 1;
        if (improvement > bestImprovement) {
          bestImprovement = improvement;
          bestI = i;
        }
      }
      if (bestI === -1) {
        // Every interval at cap. Raise cap and try again.
        if (cap < agents) {
          cap++;
          continue;
        }
        break; // truly nowhere to place; shouldn't happen for sane inputs
      }
      breaksPerShift[idx][bestI]++;
      breaks[bestI]++;
      budget--;
    }
  });

  // On-phones = (scheduled − breaks) × (1 − outOfCenterShrink)
  // The flat out-of-center reduction handles agents who aren't on the floor
  // at all (training, PTO, sick) — those can't be redirected by intraday WFM.
  return scheduled.map((s, i) =>
    Math.round((s - breaks[i]) * (1 - outOfCenterShrink)),
  );
}

// Slices an arrival curve to the active hours and runs Erlang C per interval.
// `arrivalCurve` must be a 48-element array of { label, pct }. Supports
// midnight-wrap schedules (endHour < startHour).
//
// `prioritizeOcc` switches the staffing model from dual-constraint (default,
// returns max(occ_floor, sl_floor)) to occ-only (returns ceil(erlangs/maxOcc)).
// In occ-only mode the SL target is informational — we still compute achievedSL
// per interval so the caller can warn when it drops below the target.
// Deterministic pseudo-random in [-1, 1]. Seeded by interval index so the
// chart is stable across renders (no flicker). Used to add visible
// per-interval variance to the post-AI residual demand curve — vanilla
// CAMEL × volume is too smooth to tell the "AI removes the predictable
// baseload, residual is bursty" story.
function seededNoise(i) {
  const x = Math.sin((i + 1) * 12.9898 + 78.233) * 43758.5453;
  return (x - Math.floor(x)) * 2 - 1; // [-1, 1)
}

export function computeIntervalStaffing({
  arrivalCurve,
  dailyVolume,
  ahtMins,
  startHour,
  endHour,
  targetSL,
  targetSeconds,
  maxOcc,
  shrinkage,
  prioritizeOcc = false,
  // Amplitude of per-interval call-volume noise (0 = smooth CAMEL × volume).
  // Used for post-AI scenarios where residual demand is bumpier than the
  // pre-AI baseline. scenarios.js auto-derives this from cvUplift so higher
  // containment produces a visibly choppier curve.
  volatilityNoise = 0,
}) {
  const ahtSec = ahtMins * 60;
  const active =
    endHour > startHour
      ? arrivalCurve.slice(startHour * 2, endHour * 2)
      : [
          ...arrivalCurve.slice(startHour * 2),
          ...arrivalCurve.slice(0, endHour * 2),
        ];
  const totalPct = active.reduce((s, i) => s + i.pct, 0);

  let totalRequired = 0;
  let totalScheduled = 0;
  let peak = 0;
  let minAchievedSL = 1;
  // Daily metrics are CALL-VOLUME-WEIGHTED across intervals, not min/max.
  // Industry "daily SL" is calculated as (calls answered in target) / total
  // calls — calls in busy intervals matter more than calls in quiet ones.
  // Taking the MIN per-interval natural lets a Sunday 8 AM interval with 1
  // call dictate the staffing plan for a peak Monday lunch with 100 calls,
  // which is the textbook wrong way to aggregate per-interval Erlang outputs.
  let weightedNaturalNum = 0; // Σ(natural_i × calls_i)
  let weightedSLNum = 0;       // Σ(SL_i × calls_i)
  let weightedCallsDen = 0;    // Σ(calls_i) over intervals with any traffic
  const intervals = active.map((iv, idx) => {
    const norm = iv.pct / totalPct;
    const baseCalls = dailyVolume * norm;
    // Apply seeded volatility noise. Pre-AI scenarios pass 0 and stay
    // smooth. Post-AI scenarios pass a value derived from cvUplift so the
    // residual stream shows visible interval-to-interval variance — which
    // is what actually happens when AI removes the predictable baseload.
    const noiseFactor = volatilityNoise > 0
      ? Math.max(0, 1 + seededNoise(idx) * volatilityNoise)
      : 1;
    const calls = baseCalls * noiseFactor;
    const erlangs = calls * 2 * (ahtSec / 3600);
    const req = prioritizeOcc
      ? findRequiredAgentsByOcc(erlangs, maxOcc)
      : findRequiredAgents(erlangs, ahtSec, targetSL, targetSeconds, maxOcc);
    // Compute the achieved SL at this staffing level. In dual-constraint mode
    // this is always >= targetSL by construction. In occ-only mode it may
    // drop below — that's the warning condition the calculator surfaces.
    const achievedSL =
      erlangs > 0 ? serviceLevel(req, erlangs, ahtSec, targetSeconds) : 1;
    if (erlangs > 0) {
      if (achievedSL < minAchievedSL) minAchievedSL = achievedSL;
      // sl_floor with no occ cap = the "pure SL" agent count for this interval.
      const slFloor = findRequiredAgents(
        erlangs,
        ahtSec,
        targetSL,
        targetSeconds,
        0.999,
      );
      const ivUpper = slFloor > 1 ? erlangs / (slFloor - 1) - 1e-9 : 0.95;
      // Accumulate call-weighted contributions. Intervals with more calls
      // dominate; quiet intervals contribute little.
      weightedNaturalNum += ivUpper * calls;
      weightedSLNum += achievedSL * calls;
      weightedCallsDen += calls;
    }
    const sched = Math.ceil(req / (1 - shrinkage));
    totalRequired += req;
    totalScheduled += sched;
    peak = Math.max(peak, sched);
    return {
      label: iv.label,
      required: req,
      scheduled: sched,
      calls,
      erlangs,
      achievedSL,
    };
  });
  // Call-weighted natural maxOcc. Bounded to a realistic industry range
  // [0.55, 0.95] to defend against pathological inputs (e.g. a zero-call day
  // pinning natural at the fallback default).
  const weightedNatural =
    weightedCallsDen > 0 ? weightedNaturalNum / weightedCallsDen : 0.85;
  const achievedSL =
    weightedCallsDen > 0 ? weightedSLNum / weightedCallsDen : 1;
  const naturalMaxOcc = Math.min(0.95, Math.max(0.55, weightedNatural));

  return {
    intervals,
    totalRequired,
    totalScheduled,
    peak,
    minAchievedSL,
    achievedSL, // call-weighted "daily SL" (industry-standard reporting metric)
    naturalMaxOcc,
    totalCalls: weightedCallsDen, // exposed so scenarios.js can weight across DOW
  };
}

// ─── src/lib/scenarios.js ────────────────────────────────────────────────────
const WEEKS_PER_MONTH = 4.33;

// Full DOW-weighted monthly cost for one scenario (Pre/Post AI × Trad/Gig).
// `dow` is { Mon: 16.5, Tue: 15.5, ... } where each value is % of weekly
// volume (0 = closed). Per-DOW Erlang C + shift-block solve, weighted by
// 4.33 weeks/month. Visualization data (intervals, shifts) comes from the
// peak day so the charts always show the worst-case staffing pattern.
//
// Cost model (canonical, ported from the v15 calculator):
//   sup/mgr/wfm headcount = ceil(peakTradAgents / ratio), min 1 when ratio is finite.
//   support cost (monthly) = (supCount*supSalary + mgrCount*mgrSalary + wfmCount*wfmSalary) / 12
//   workstation cost (monthly) = peakTradAgents * (workstationCost / equipmentLife)
//   traditional cost = scheduledHours*loadedRate + support + workstation
// To disable a support tier, pass agentsPerMgr/Wfm = Infinity.
export function computeScenarioCost({
  arrivalCurve,
  monthlyVolume,
  ahtMins,
  startHour,
  endHour,
  dow,
  gigTiers,
  targetSL,
  targetSeconds,
  maxOcc,
  shrinkage,
  shiftLength,
  influxTarget = 1.2,
  traditionalRate,
  benefitsMultiplier,
  agentsPerSup,
  agentsPerMgr = Infinity,
  agentsPerWfm = Infinity,
  supSalary = 0,
  mgrSalary = 0,
  wfmSalary = 0,
  workstationCost = 1700,
  equipmentLife = 60,
  aiEnabled,
  containmentRate,
  escalationRate,
  // AHT inflation is now derived from a log-normal distribution model
  // rather than a fixed multiplier. `ahtCV` is the coefficient of variation
  // (σ/μ) of the call-duration distribution; AI removes the bottom portion
  // (easy calls) and the residual mean shifts up automatically. Default
  // 0.6 matches industry voice-call spread. The legacy `ahtFactor` knob is
  // gone — too crude, didn't auto-adjust with containment.
  ahtCV = 0.6,
  aiCostPerMin,
  postAiWagePremium = 0,
  // Peakedness-style variability buffer for the residual human arrival stream.
  // When AI removes the predictable baseload, the same absolute σ over a
  // smaller μ means coefficient of variation rises by ~ monthlyVolume /
  // humanVolume. Vanilla Erlang C assumes Poisson arrivals (peakedness z = 1)
  // and under-staffs in this regime. We gross dailyVol up by α × CV-uplift
  // before Erlang C runs, which forces the solver to schedule a real-world
  // buffer for that volatility. This is a simplified linear approximation in
  // the spirit of Hayward's overflow-traffic approximation (1952) and the
  // peakedness-based staffing rules in Schrieck, Akşin & Chevalier, POMS 2014
  // — it's NOT a precise Hayward implementation. α = 0.10 is a moderate
  // calibration to industry CV data; set α = 0 to recover pure Erlang C
  // (Poisson-arrival) behavior. No effect on pre-AI scenarios because
  // cvUplift = 0 when humanVolume = monthlyVolume.
  volatilityAlpha = 0.10,
  // When true, staffing uses occupancy as the binding constraint (ceil(erlangs/
  // maxOcc)) instead of the dual occ + SL floor. SL becomes an output metric
  // (minAchievedSL) that the caller can compare to targetSL and surface as a
  // warning. The calculator passes true and auto-positions its maxOcc slider
  // at naturalMaxOcc (the sweet spot where SL just meets target).
  prioritizeOcc = false,
}) {
  const contained = aiEnabled ? monthlyVolume * containmentRate : 0;
  const escalated = aiEnabled ? contained * escalationRate : 0;
  const humanVolume = monthlyVolume - contained + escalated;
  // Residual AHT after AI removes the easy/short calls from the bottom of
  // the log-normal distribution. Cutoff = NET containment (calls actually
  // resolved by AI = contained × (1 − escalation)); escalated calls bounce
  // back to humans and re-enter the residual mix. The conditional mean of
  // what remains above the cutoff is the new human AHT.
  const netContainment = aiEnabled
    ? containmentRate * (1 - escalationRate)
    : 0;
  const humanAHT = aiEnabled
    ? lognormalConditionalMean(ahtMins, ahtCV, netContainment)
    : ahtMins;
  // Derived AHT factor (output, for the UI to display). Was the old input.
  const ahtFactor = ahtMins > 0 ? humanAHT / ahtMins : 1;

  const cvUplift = humanVolume > 0 ? Math.max(0, monthlyVolume / humanVolume - 1) : 0;
  const volatilityBuffer = 1 + volatilityAlpha * cvUplift;
  // Visual per-interval noise on the residual demand curve. Auto-scales with
  // cvUplift and caps at ±30% so the chart can't go fully chaotic. Pre-AI
  // scenarios (cvUplift = 0) stay smooth. Post-AI at default 60% containment
  // (cvUplift ≈ 1.5) gets ±30%, which is the visual story we need to show
  // why even a perfectly tuned WFM team can't tame the residual stream.
  const volatilityNoise = aiEnabled ? Math.min(0.30, cvUplift * 0.20) : 0;

  const aiHandledCalls = contained - escalated;
  const aiMonthlyCost = aiHandledCalls * ahtMins * aiCostPerMin;

  const effectiveRate = aiEnabled
    ? traditionalRate * (1 + postAiWagePremium / 100)
    : traditionalRate;
  const loadedRate = effectiveRate * (1 + benefitsMultiplier / 100);

  const dowEntries = Object.entries(dow);
  const dowTotal = dowEntries.reduce((s, [, v]) => s + v, 0);
  const weeklyHumanVolume = humanVolume / WEEKS_PER_MONTH;

  let monthlyGigHours = 0;
  let monthlyShiftHours = 0;
  let peakDayVolume = 0;
  let peakIntervals = null;
  let peakShiftData = null;
  let peakAvgFTE = 0;
  let peakTradAgents = 0;
  let minAchievedSL = 1;
  // Call-weighted aggregation across DOW. Industry "daily SL" is calls-in-
  // target / total-calls — busy days dominate. Taking MIN across DOW lets a
  // quiet Sunday set the model for a peak Monday, which is the textbook
  // wrong way to aggregate.
  let dowWeightedNaturalNum = 0;
  let dowWeightedSLNum = 0;
  let dowWeightedCallsDen = 0;

  // Calibration: find the geometry-buffer multiplier K such that solver
  // delivers target SL at coverage = 1.0 *when maxOcc is at its natural
  // value*. We DO NOT recompute K when the user changes maxOcc — that would
  // make the model auto-compensate for maxOcc changes and the slider would
  // do nothing to SL. K should be a "shift geometry inefficiency" constant
  // that depends on the demand curve and shift menu, not the occupancy
  // ceiling.
  //
  // So when the user moves maxOcc above natural, intervals[i].required drops
  // (Erlang C lets agents run hotter) → solver staffs less at the same K →
  // delivered SL drops. When user moves maxOcc below natural, more required
  // → solver staffs more → SL exceeds target. The Coverage Target slider
  // then layers on top: 1.00 = baseline (calibrated), <1 = save cost / miss
  // SL, >1 = over-provision.
  let calibrationK = 1.0;
  const ahtSec = humanAHT * 60;
  const inCenter = shrinkage * 0.60;
  const outOfCenter = shrinkage * 0.40;
  if (dowEntries.length > 0) {
    const peakEntry = dowEntries.reduce(
      (max, e) => (e[1] > max[1] ? e : max),
      ["", 0],
    );
    if (peakEntry[1] > 0) {
      const peakDailyVol = weeklyHumanVolume * (peakEntry[1] / dowTotal);
      const peakStaffingVol = peakDailyVol * volatilityBuffer;
      // Step 1: discover the workload's natural maxOcc by running staffing
      // with no occ cap (maxOcc=0.99). naturalMaxOcc is purely a function of
      // the demand curve + SL target + AHT, NOT the user's maxOcc input.
      const { naturalMaxOcc: refNatural } = computeIntervalStaffing({
        arrivalCurve,
        dailyVolume: peakStaffingVol,
        ahtMins: humanAHT,
        startHour,
        endHour,
        targetSL,
        targetSeconds,
        maxOcc: 0.99,
        shrinkage,
        prioritizeOcc,
        volatilityNoise,
      });
      // Step 2: compute calibration intervals at maxOcc = refNatural. The K
      // we find here is the geometry buffer relative to "SL-meeting" staffing.
      const { intervals: cIntervals } = computeIntervalStaffing({
        arrivalCurve,
        dailyVolume: peakStaffingVol,
        ahtMins: humanAHT,
        startHour,
        endHour,
        targetSL,
        targetSeconds,
        maxOcc: refNatural,
        shrinkage,
        prioritizeOcc,
        volatilityNoise,
      });
      const cRequired = cIntervals.map((iv) => iv.required);
      let lo = 0.5;
      let hi = 2.5;
      for (let it = 0; it < 12; it++) {
        const mid = (lo + hi) / 2;
        const r = solveShiftBlocks(cIntervals, shiftLength, shrinkage, mid);
        const op = computeOnPhones(
          r.shiftDefs,
          r.shiftAgents,
          cIntervals.length,
          inCenter,
          outOfCenter,
          cRequired,
        );
        let slSum = 0;
        let cSum = 0;
        for (let j = 0; j < cIntervals.length; j++) {
          const iv = cIntervals[j];
          if (iv.calls <= 0 || iv.erlangs <= 0) continue;
          const sl =
            op[j] > 0
              ? serviceLevel(op[j], iv.erlangs, ahtSec, targetSeconds)
              : 0;
          slSum += sl * iv.calls;
          cSum += iv.calls;
        }
        const ds = cSum > 0 ? slSum / cSum : 1;
        if (ds >= targetSL) hi = mid;
        else lo = mid;
      }
      calibrationK = (lo + hi) / 2;
    }
  }
  const effectiveCoverage = calibrationK * influxTarget;

  for (const [, pct] of dowEntries) {
    if (pct <= 0) continue;
    const dailyVol = weeklyHumanVolume * (pct / dowTotal);
    // Peakedness-style buffer: inflate the volume Erlang C sees so it
    // schedules for the residual stream's higher CV. Equivalent to "pretend
    // traffic is buffer× larger for staffing purposes only." Gig and trad
    // both pay the buffer because both feed off the same Erlang C requirement.
    const stafingVol = dailyVol * volatilityBuffer;

    const {
      intervals,
      totalRequired,
      minAchievedSL: dayMinSL,
      achievedSL: dayAchievedSL,
      naturalMaxOcc: dayNaturalMaxOcc,
      totalCalls: dayCalls,
    } = computeIntervalStaffing({
      arrivalCurve,
      dailyVolume: stafingVol,
      ahtMins: humanAHT,
      startHour,
      endHour,
      targetSL,
      targetSeconds,
      maxOcc,
      shrinkage,
      prioritizeOcc,
      volatilityNoise,
    });
    const {
      dailyShiftHours,
      avgFTE,
      shiftAgents,
      shiftDefs,
      scheduledPerInterval,
      shiftMetrics,
    } = solveShiftBlocks(intervals, shiftLength, shrinkage, effectiveCoverage);

    // DELIVERED SL — recompute SL using what the shift solver actually
    // staffed AFTER smart break placement (lunches concentrated during
    // overlap valleys, so on-phones stays high at peaks). This makes the
    // Coverage Target slider affect the SL display correctly:
    //   • 100% coverage → on-phones ≈ Erlang C req at peaks → SL hits target
    //   • 95%  coverage → fewer scheduled bodies → on-phones drops at peaks
    //                     → SL drops below target → warning fires
    //
    // We assume a 60/40 split of total shrinkage into in-center vs out-of-
    // center (matches the calculator's 21/14 default). The 60% is placed
    // via the break-placement optimizer; the 40% is a flat reduction
    // (training/PTO/sick — not on the floor).
    // inCenter / outOfCenter / ahtSec declared at function scope above.
    const dayOnPhones = computeOnPhones(
      shiftDefs,
      shiftAgents,
      intervals.length,
      inCenter,
      outOfCenter,
      intervals.map((iv) => iv.required),
    );
    let dayDeliveredSLNum = 0;
    let dayDeliveredCalls = 0;
    let dayDeliveredMinSL = 1;
    for (let i = 0; i < intervals.length; i++) {
      const iv = intervals[i];
      if (iv.calls <= 0 || iv.erlangs <= 0) continue;
      const effOnPhones = dayOnPhones[i] || 0;
      const sl = effOnPhones > 0
        ? serviceLevel(effOnPhones, iv.erlangs, ahtSec, targetSeconds)
        : 0;
      dayDeliveredSLNum += sl * iv.calls;
      dayDeliveredCalls += iv.calls;
      if (sl < dayDeliveredMinSL) dayDeliveredMinSL = sl;
    }
    const dayDeliveredSL =
      dayDeliveredCalls > 0 ? dayDeliveredSLNum / dayDeliveredCalls : 1;

    if (dayDeliveredMinSL < minAchievedSL) minAchievedSL = dayDeliveredMinSL;
    if (dayCalls > 0) {
      dowWeightedNaturalNum += dayNaturalMaxOcc * dayCalls;
      dowWeightedSLNum += dayDeliveredSL * dayCalls;
      dowWeightedCallsDen += dayCalls;
    }

    monthlyGigHours += totalRequired * 0.5 * WEEKS_PER_MONTH;
    monthlyShiftHours += dailyShiftHours * WEEKS_PER_MONTH;

    // Peak concurrent headcount across the bathtub — used for sup/mgr/wfm
    // ratios and workstation seat count (you need enough desks for the
    // busiest interval, not the average).
    const dayPeakTrad = scheduledPerInterval.length
      ? Math.max(...scheduledPerInterval)
      : 0;
    if (dayPeakTrad > peakTradAgents) peakTradAgents = dayPeakTrad;

    if (dailyVol > peakDayVolume) {
      peakDayVolume = dailyVol;
      peakIntervals = intervals;
      peakAvgFTE = avgFTE;
      peakShiftData = {
        shiftAgents,
        shiftDefs,
        scheduledPerInterval,
        shiftMetrics,
      };
    }
  }

  // Finalize call-weighted aggregates across DOW.
  const naturalMaxOcc =
    dowWeightedCallsDen > 0
      ? Math.min(0.95, Math.max(0.55, dowWeightedNaturalNum / dowWeightedCallsDen))
      : 0.85;
  const achievedSL =
    dowWeightedCallsDen > 0 ? dowWeightedSLNum / dowWeightedCallsDen : 1;

  const weeklyGigHours = monthlyGigHours / WEEKS_PER_MONTH;
  const sortedTiers = [...gigTiers].sort((a, b) => b.minHours - a.minHours);
  const activeTier =
    sortedTiers.find((t) => weeklyGigHours >= t.minHours) ||
    sortedTiers[sortedTiers.length - 1];
  const gigRate = activeTier.rate;

  const gigCost = monthlyGigHours * gigRate;

  const openDaysPerWeek = dowEntries.filter(([, v]) => v > 0).length;
  const workDaysPerMonth = openDaysPerWeek * WEEKS_PER_MONTH;

  const supCount = Number.isFinite(agentsPerSup)
    ? Math.max(1, Math.ceil(peakTradAgents / agentsPerSup))
    : 0;
  const mgrCount = Number.isFinite(agentsPerMgr)
    ? Math.max(1, Math.ceil(peakTradAgents / agentsPerMgr))
    : 0;
  const wfmCount = Number.isFinite(agentsPerWfm)
    ? Math.max(1, Math.ceil(peakTradAgents / agentsPerWfm))
    : 0;
  const supportCostMonthly =
    (supCount * supSalary + mgrCount * mgrSalary + wfmCount * wfmSalary) / 12;
  const workstationCostMonthly =
    peakTradAgents * (workstationCost / Math.max(1, equipmentLife));
  const traditionalCost =
    monthlyShiftHours * loadedRate + supportCostMonthly + workstationCostMonthly;

  const vols = (peakIntervals || []).map((iv) => iv.calls);
  const mean = vols.reduce((s, v) => s + v, 0) / (vols.length || 1);
  const variance =
    vols.reduce((s, v) => s + (v - mean) ** 2, 0) / (vols.length || 1);
  const cv = mean > 0 ? Math.sqrt(variance) / mean : 0;

  return {
    humanVolume,
    humanAHT,
    ahtFactor, // derived multiplier (humanAHT / base ahtMins) — for UI display
    aiMonthlyCost,
    aiHandledCalls,
    cvUplift,
    volatilityBuffer,
    minAchievedSL, // worst-case SL across intervals (kept for diagnostics)
    achievedSL,    // call-weighted "daily SL" — the industry-standard reporting number
    naturalMaxOcc,
    monthlyRequiredHours: monthlyGigHours,
    monthlyScheduledHours: monthlyShiftHours,
    avgFTE: peakAvgFTE,
    peakTradAgents,
    supCount,
    mgrCount,
    wfmCount,
    supportCostMonthly,
    workstationCostMonthly,
    traditionalCost,
    gigCost,
    gigRate,
    activeTierLabel: activeTier.label,
    weeklyGigHours,
    workDaysPerMonth,
    traditionalTotal: traditionalCost + aiMonthlyCost,
    gigTotal: gigCost + aiMonthlyCost,
    cv,
    intervals: peakIntervals || [],
    loadedRate,
    ...(peakShiftData || {}),
  };
}

// ─── src/lib/presets.js ──────────────────────────────────────────────────────
// AI cost-stack presets surfaced as tier buttons in the AI calculator. Each
// preset is one production-ready vendor combination with realistic per-minute
// pricing for SIP, STT, LLM, TTS, orchestration, compliance, and a failure
// retry buffer.
export const TIER_PRESETS = {
  lean: {
    label: "Lean Stack",
    range: "$0.06 – $0.10",
    color: "#22c55e",
    desc: "Telnyx + Deepgram + GPT-4o-mini + OpenAI TTS. Self-hosted orchestration.",
    vendors: "Telnyx · Deepgram · GPT-4o-mini · OpenAI TTS · Pipecat",
    costs: {
      aiSIP: 0.002,
      aiSTT: 0.007,
      aiLLM: 0.002,
      aiTTS: 0.008,
      aiOrchestration: 0.04,
      aiCompliance: 0.001,
      aiFailureBuffer: 3,
    },
  },
  standard: {
    label: "Standard Production",
    range: "$0.10 – $0.18",
    color: "#f59e0b",
    desc: "Retell/Deepgram platform + GPT-4o + Cartesia. Mid-market default.",
    vendors: "Twilio · Deepgram · GPT-4o · Cartesia · Retell",
    costs: {
      aiSIP: 0.005,
      aiSTT: 0.008,
      aiLLM: 0.005,
      aiTTS: 0.015,
      aiOrchestration: 0.105,
      aiCompliance: 0.002,
      aiFailureBuffer: 5,
    },
  },
  premium: {
    label: "Premium Quality",
    range: "$0.18 – $0.35",
    color: "#ef4444",
    desc: "Vapi + GPT-4o + ElevenLabs HD voice. Brand-sensitive deployments.",
    vendors: "Twilio · Azure STT · GPT-4o · ElevenLabs v2 · Vapi",
    costs: {
      aiSIP: 0.009,
      aiSTT: 0.015,
      aiLLM: 0.008,
      aiTTS: 0.06,
      aiOrchestration: 0.15,
      aiCompliance: 0.003,
      aiFailureBuffer: 8,
    },
  },
};

// ShyftOff rate: flat $35/hr loaded, regardless of AI tier or volume.
// The lib's tier-selection mechanism is kept for backward compatibility
// but only one entry is needed at this rate. To restore tiered pricing
// later, just add more {minHours, rate, label} entries; lib selects the
// highest minHours-threshold the weekly hours qualify for.
export const DEFAULT_GIG_TIERS = [
  { minHours: 0, rate: 35.0, label: "ShyftOff Standard" },
];

